services:
  dev:
    image: lemonaderoom/claude-code:latest
    environment:
      GH_TOKEN: ${GH_TOKEN}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_SESSION_TOKEN: ${AWS_SESSION_TOKEN}
    ports:
      - '127.0.0.1:8080:8080'
      - '127.0.0.1:3001:3001'
    tty: true
    volumes:
      - 'home:/claude'
      - '.:/claude/workspace'
      - '${HOME}/.claude:/claude/.claude'
      - '${HOME}/.claude.json:/claude/.claude.json'
      - '${HOME}/.gitconfig:/claude/.gitconfig'
      - '/var/run/docker.sock:/var/run/docker.sock'
      - 'server_build_cache:/claude/workspace/Server/.build'

volumes:
  home:
  server_build_cache:
