services:
  dev:
    image: lemonaderoom/claude-code:latest
    environment:
      GH_TOKEN: ${GH_TOKEN}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_SESSION_TOKEN: ${AWS_SESSION_TOKEN}
    ports:
      - '127.0.0.1:8080:8080'
      - '127.0.0.1:3001:3001'
#      - "127.0.0.1:16686:16686"
    tty: true
    stdin_open: true
    volumes:
      - '.:/claude/workspace'
      - '${HOME}/.claude:/claude/.claude'
      - '${HOME}/.claude.json:/claude/.claude.json'
      - '/var/run/docker.sock:/var/run/docker.sock'
      - 'cqrs_es_example_swift_build_cache:/claude/workspace/Server/.build'

volumes:
  cqrs_es_example_swift_build_cache:
