openapi: 3.0.3

info:
  title: CQRS ES Example Swift Command Server
  version: 1.0.0

servers:
  - url: http://127.0.0.1:3001/command
    description: Local
  - url: https://5c54t4fft3.execute-api.ap-northeast-1.amazonaws.com/Stage/command
    description: Staging

paths:
  /v1/healthcheck:
    get:
      responses:
        200:
          description: Server Running
          content:
            text/plain:
              schema:
                type: string
                example: Command Server Working!
