AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: CQRS ES Example Swift

Globals:
  Function:
    Architectures:
      - arm64
    Timeout: 3
    MemorySize: 128
    Tracing: Active
    LoggingConfig:
      ApplicationLogLevel: DEBUG
      LogFormat: JSON
Parameters:
  CommandServerFunctionImageUri:
    Type: String
    Description: ECR URI for Command
  QueryServerFunctionImageUri:
    Type: String
    Description: ECR URI for Query
  ServerEnvironment:
    Type: String
    Description: Serverの環境（Staging)
Resources:
  ServerHttpApi:
    Type: AWS::Serverless::HttpApi
    Properties:
      Name: CQRS ES Example Swift Server
      StageName: Stage
  CommandServerFunction:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Image
      ImageUri: !Ref CommandServerFunctionImageUri
      # Layerはコンテナイメージでは使用できないため、
      # X-Rayへの送信はアプリケーション内のOpenTelemetryから直接行います
      Environment:
        Variables:
          SERVER: !Ref ServerEnvironment
          AWS_XRAY_CONTEXT_MISSING: LOG_ERROR
          # CloudWatch Application SignalsのOTLPエンドポイントを使用
          OTEL_EXPORTER_OTLP_ENDPOINT: !Sub https://xray.${AWS::Region}.amazonaws.com
          # X-RayのトレースIDフォーマットを使用
          OTEL_PROPAGATORS: xray
          # VaporのLogLevelをDEBUGに設定
          LOG_LEVEL: DEBUG
      Policies:
        - AWSXRayDaemonWriteAccess
        - Statement:
          - Effect: Allow
            Action:
              - xray:PutTraceSegments
              - xray:PutTelemetryRecords
            Resource: '*'
      Events:
        CommandHttpApi:
          Type: HttpApi
          Properties:
            ApiId: !Ref ServerHttpApi
            Method: ANY
            Path: /command/{proxy+}
  QueryServerFunction:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Image
      ImageUri: !Ref QueryServerFunctionImageUri
      # Layerはコンテナイメージでは使用できないため、
      # X-Rayへの送信はアプリケーション内のOpenTelemetryから直接行います
      Environment:
        Variables:
          SERVER: !Ref ServerEnvironment
          AWS_XRAY_CONTEXT_MISSING: LOG_ERROR
          # CloudWatch Application SignalsのOTLPエンドポイントを使用
          OTEL_EXPORTER_OTLP_ENDPOINT: !Sub https://xray.${AWS::Region}.amazonaws.com
          # X-RayのトレースIDフォーマットを使用
          OTEL_PROPAGATORS: xray
          # VaporのLogLevelをDEBUGに設定
          LOG_LEVEL: DEBUG
      Policies:
        - AWSXRayDaemonWriteAccess
        - Statement:
          - Effect: Allow
            Action:
              - xray:PutTraceSegments
              - xray:PutTelemetryRecords
            Resource: '*'
      Events:
        QueryHttpApi:
          Type: HttpApi
          Properties:
            ApiId: !Ref ServerHttpApi
            Method: ANY
            Path: /query/{proxy+}