version: 0.2

env:
  shell: bash

exported-variables:
  - IMAGE_URI

phases:
  pre_build:
    commands:
      - aws ecr get-login-password --region "$AWS_REGION" | docker login --username AWS --password-stdin "$REPOSITORY_URL"

  build:
    commands:
      - docker build --file "$DOCKERFILE_PATH" --tag "$REPOSITORY_URL:$TAG" ./Server

  post_build:
    commands:
      - docker push "$REPOSITORY_URL:$TAG"
      - |
        DIGEST=$(aws ecr describe-images \
          --repository-name $(echo $REPOSITORY_URL | cut -d'/' -f2-) \
          --image-ids imageTag=$TAG \
          --query 'imageDetails[0].imageDigest' --output text)
      - IMAGE_URI=$REPOSITORY_URL@$DIGEST
      - echo "IMAGE_URI=$IMAGE_URI"

cache:
  modes:
    - LOCAL_DOCKER_LAYER_CACHE
