version: 0.2

env:
  shell: bash
  variables:
    BUILDER_NAME: codebuild
  exported-variables:
    - IMAGE_URI

phases:
  install:
    commands:
      - docker buildx version || docker buildx install
      - docker buildx create --name "$BUILDER_NAME" --use

  pre_build:
    commands:
      - aws ecr get-login-password --region "$AWS_REGION" | docker login --username AWS --password-stdin "$REPOSITORY_URL"
      - export CACHE_IMAGE="${REPOSITORY_URL}:cache"
      - docker pull "$CACHE_IMAGE" || true

  build:
    commands:
      - |
        docker buildx build \
          --builder "$BUILDER_NAME" \
          --platform linux/arm64 \
          --file "$DOCKERFILE_PATH" \
          --tag "$REPOSITORY_URL:$TAG" \
          --cache-from "type=registry,ref=$CACHE_IMAGE" \
          --cache-to   "type=registry,ref=$CACHE_IMAGE,mode=max" \
          --output     "type=registry,push=true" \
          ./Server

  post_build:
    commands:
      - |
        DIGEST=$(aws ecr describe-images \
          --repository-name $(echo $REPOSITORY_URL | cut -d'/' -f2-) \
          --image-ids imageTag=$TAG \
          --query 'imageDetails[0].imageDigest' --output text)
      - export "IMAGE_URI=$REPOSITORY_URL@$DIGEST"
      - echo "IMAGE_URI=$IMAGE_URI"
