version: 0.2

phases:
  pre_build:
    commands:
      # 環境変数の設定
      - export REPOSITORY_URI=$AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$ECR_REPOSITORY_NAME

      # ECRへのログイン
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com

  build:
    commands:
      # Dockerイメージのビルドとプッシュ
      - |
        docker buildx build \
          --platform linux/arm64 \
          --cache-from type=registry,ref=$REPOSITORY_URI:cache-buildkit \
          --cache-from type=registry,ref=$REPOSITORY_URI:latest \
          --cache-to type=registry,ref=$REPOSITORY_URI:cache-buildkit,mode=max \
          --tag $REPOSITORY_URI:latest \
          --tag $REPOSITORY_URI:$CODEBUILD_RESOLVED_SOURCE_VERSION \
          --push \
          --progress=plain \
          -f Server/terraform/Dockerfile .

