version: 0.2

cache:
  paths:
    - 'Server/.build/**/*'

phases:
  install:
    commands:
      - |
        export DEBIAN_FRONTEND=noninteractive DEBCONF_NONINTERACTIVE_SEEN=true \
            && apt-get -q update \
            && apt-get -q dist-upgrade -y \
            && apt-get install -y \
            libjemalloc-dev \
            libssl-dev \
            openssl \
            pkg-config
  pre_build:
    commands:
      - export REPOSITORY_URI=$AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$ECR_REPOSITORY_NAME
      - docker buildx create --use --driver docker-container --platform linux/arm64
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com

  build:
    commands:
      - cd Server
      - |
        swift build \
          -c release \
          --product CommandServer \
          --build-path .build \
          --static-swift-stdlib \
          -Xlinker -ljemalloc
      - cp "$(swift build --package-path /build -c release --show-bin-path)/CommandServer" ./App
      - |
        docker buildx build \
          --platform linux/arm64 \
          --cache-from type=registry,ref=$REPOSITORY_URI:cache-buildkit \
          --cache-to type=registry,ref=$REPOSITORY_URI:cache-buildkit,mode=max \
          --tag $REPOSITORY_URI:latest \
          --tag $REPOSITORY_URI:$CODEBUILD_RESOLVED_SOURCE_VERSION \
          --provenance=false --sbom=false \
          --output "type=registry,push=true,oci-mediatypes=false" \
          --progress=plain \
          -f Server/terraform/Dockerfile .

